-- OTwoOne — Client Portal Schema
-- Extends projects with intake tracking columns and creates project_intakes
-- to back the /projects/[token] portal.
--
-- Safe for production:
--   • All new columns on projects have defaults or are nullable — no back-fill needed.
--   • The NOT NULL columns (type, intake_status) carry a DEFAULT so existing rows
--     receive the default value at ALTER time without a separate UPDATE.
--   • project_intakes is a net-new table, nothing to migrate.
--   • set_updated_at() was created in 20260303_add_updated_at.sql with
--     CREATE OR REPLACE and is reused here — no redefinition needed.
--   • All statements use IF NOT EXISTS / ADD COLUMN IF NOT EXISTS guards so
--     the migration is safe to re-run.

-- ─── Extend projects ──────────────────────────────────────────────────────────

-- Project service type (determines portal copy / booking variant in future)
alter table projects
  add column if not exists type text not null default 'foundation'
  check (type in ('launch', 'foundation', 'growth', 'accelerator'));

-- Opaque token sent to clients — maps URL /projects/[token] to a project row.
-- Generated by the application on first portal dispatch; nullable for existing rows.
alter table projects
  add column if not exists intake_token uuid unique;

-- Coarse intake lifecycle so the hub can track where a client is in the portal.
alter table projects
  add column if not exists intake_status text not null default 'not_sent'
  check (intake_status in ('not_sent', 'sent', 'in_progress', 'complete'));

-- Timestamp of the most recent auto-save from the portal (any step).
alter table projects
  add column if not exists intake_last_saved_at timestamptz;

-- Client contact details captured directly in the portal (may differ from
-- the original lead contact if someone else fills in the intake).
alter table projects
  add column if not exists client_contact_name text;

alter table projects
  add column if not exists client_contact_email text;

-- ─── project_intakes ──────────────────────────────────────────────────────────

-- One row per project; each step's answers are stored as a JSON object so
-- step definitions can evolve without schema changes.
-- step1 = Basics (name, project name, goals — already in the portal UI)
-- step2 = reserved for next portal step
-- step3 = reserved

create table if not exists project_intakes (
  project_id    uuid        primary key references projects(id) on delete cascade,
  step1         jsonb       not null default '{}'::jsonb,
  step2         jsonb       not null default '{}'::jsonb,
  step3         jsonb       not null default '{}'::jsonb,
  completed_at  timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ─── Trigger: project_intakes ─────────────────────────────────────────────────
--
-- Reuse set_updated_at() defined in 20260303_add_updated_at.sql.
-- DROP IF EXISTS + CREATE ensures idempotency on re-runs.

drop trigger if exists project_intakes_set_updated_at on project_intakes;

create trigger project_intakes_set_updated_at
  before update on project_intakes
  for each row
  execute procedure set_updated_at();
